"""add fk indexes and professional patient constraints

Revision ID: 693767523ad6
Revises: 387f2be3849c
Create Date: 2026-09-14 22:05:35.239457

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693767523ad6"
down_revision: str | None = "387f2be3849c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_achievement_log_achievement_id"),
        "achievement_log",
        ["achievement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_achievement_log_user_id"), "achievement_log", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_session_activity_id"), "activity_session", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_session_user_id"), "activity_session", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_diary_entry_mood_log_id"), "diary_entry", ["mood_log_id"], unique=False
    )
    op.create_index(op.f("ix_diary_entry_user_id"), "diary_entry", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_emergency_contact_user_id"), "emergency_contact", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_good_practice_log_good_practice_id"),
        "good_practice_log",
        ["good_practice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_good_practice_log_user_id"), "good_practice_log", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_mood_log_user_id"), "mood_log", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_professional_patient_patient_id"),
        "professional_patient",
        ["patient_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_professional_patient_professional_patient",
        "professional_patient",
        ["professional_id", "patient_id"],
    )
    op.create_check_constraint(
        "ck_professional_patient_not_self", "professional_patient", "professional_id <> patient_id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_professional_patient_not_self", "professional_patient", type_="check")
    op.drop_constraint(
        "uq_professional_patient_professional_patient", "professional_patient", type_="unique"
    )
    op.drop_index(op.f("ix_professional_patient_patient_id"), table_name="professional_patient")
    op.drop_index(op.f("ix_mood_log_user_id"), table_name="mood_log")
    op.drop_index(op.f("ix_good_practice_log_user_id"), table_name="good_practice_log")
    op.drop_index(op.f("ix_good_practice_log_good_practice_id"), table_name="good_practice_log")
    op.drop_index(op.f("ix_emergency_contact_user_id"), table_name="emergency_contact")
    op.drop_index(op.f("ix_diary_entry_user_id"), table_name="diary_entry")
    op.drop_index(op.f("ix_diary_entry_mood_log_id"), table_name="diary_entry")
    op.drop_index(op.f("ix_activity_session_user_id"), table_name="activity_session")
    op.drop_index(op.f("ix_activity_session_activity_id"), table_name="activity_session")
    op.drop_index(op.f("ix_achievement_log_user_id"), table_name="achievement_log")
    op.drop_index(op.f("ix_achievement_log_achievement_id"), table_name="achievement_log")
    # ### end Alembic commands ###
