"""make user profile fields nullable

Revision ID: 71d8ecdd3b13
Revises: b618abecc235
Create Date: 2026-09-05 23:39:25.953403

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71d8ecdd3b13"
down_revision: str | None = "b618abecc235"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "full_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "user",
        "gender",
        existing_type=postgresql.ENUM(
            "MALE", "FEMALE", "NON_BINARY", "OTHER", "PREFER_NOT_TO_SAY", name="gender"
        ),
        nullable=True,
    )
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "user",
        "gender",
        existing_type=postgresql.ENUM(
            "MALE", "FEMALE", "NON_BINARY", "OTHER", "PREFER_NOT_TO_SAY", name="gender"
        ),
        nullable=False,
    )
    op.alter_column("user", "full_name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
