"""add daily_reminder_enabled

Revision ID: 8317b5864c76
Revises: f3a3f411b055
Create Date: 2026-09-12 11:42:25.762824

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8317b5864c76"
down_revision: str | None = "f3a3f411b055"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("daily_reminder_enabled", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "daily_reminder_enabled")
    # ### end Alembic commands ###
