"""Refactor Breathing Tables

Revision ID: ba3ad1b001d7
Revises: 387f2be3849c
Create Date: 2026-09-18 11:38:59.624587

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba3ad1b001d7"
down_revision: str | None = "387f2be3849c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE activity_type RENAME VALUE 'BREATH' TO 'BREATHING'")
    op.create_table(
        "breathing_activity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inhale_seconds", sa.Integer(), nullable=False),
        sa.Column("hold_seconds", sa.Integer(), nullable=False),
        sa.Column("exhale_seconds", sa.Integer(), nullable=False),
        sa.Column("repeat_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["activity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("breath_activity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breath_activity",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("inhale_seconds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("hold_seconds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exhale_seconds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("repeat_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["id"], ["activity.id"], name=op.f("breath_activity_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("breath_activity_pkey")),
    )
    op.drop_table("breathing_activity")
    # ### end Alembic commands ###
