"""add email confirmation

Revision ID: c67ea0b3afd1
Revises: 387f2be3849c
Create Date: 2026-09-24 17:56:15.661118

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c67ea0b3afd1"
down_revision: str | None = "387f2be3849c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_confirmation_code",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index(
        op.f("ix_email_confirmation_code_user_id"),
        "email_confirmation_code",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "user", sa.Column("email_confirmed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_confirmed_at")
    op.drop_index(op.f("ix_email_confirmation_code_user_id"), table_name="email_confirmation_code")
    op.drop_table("email_confirmation_code")
    # ### end Alembic commands ###
