"""update user fields

Revision ID: f3a3f411b055
Revises: b618abecc235
Create Date: 2026-09-06 17:38:38.277843

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a3f411b055"
down_revision: str | None = "b618abecc235"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "full_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("user", "password", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone_number", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "password", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("user", "full_name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
